"""End-to-end orchestration for TargetIntel-IO."""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

os.environ.setdefault(
    "MPLBACKEND",
    "Agg",
)

from targetintel.feature_table import (
    build_feature_table,
    save_feature_table,
)
from targetintel.evidence.pipeline_integration import load_evidence_cards
from targetintel.html_reports import (
    write_top_html_reports,
)
from targetintel.hypothesis_cards import (
    write_top_target_cards,
)
from targetintel.intent_ranking import (
    build_intent_rankings,
    save_ranked_targets,
)
from targetintel.visualization import (
    generate_summary_figures,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class PipelineOutputs:
    """Paths generated by the end-to-end workflow."""

    feature_table: Path
    ranked_targets: Path
    target_cards_dir: Path
    html_reports_dir: Path
    figures_dir: Path
    benchmark_dir: Path | None = None
    sensitivity_dir: Path | None = None


def _validate_positive_integer(
    name: str,
    value: int,
) -> None:
    if value <= 0:
        raise ValueError(
            f"{name} must be greater than zero."
        )


def _run_command(
    command: Sequence[str],
    *,
    project_root: Path,
) -> None:
    """Run one pipeline command and fail immediately on errors."""
    printable_command = shlex.join(
        str(part)
        for part in command
    )

    print()
    print("=" * 78)
    print(f"$ {printable_command}")
    print("=" * 78)

    environment = os.environ.copy()
    environment.setdefault(
        "MPLBACKEND",
        "Agg",
    )

    subprocess.run(
        list(command),
        cwd=project_root,
        check=True,
        env=environment,
    )


def run_core_pipeline(
    *,
    page_size: int = 100,
    max_pages: int = 3,
    refresh: bool = False,
    top_n_per_mode: int = 10,
    evidence_store_path: str | Path | None = None,
    project_root: Path = PROJECT_ROOT,
) -> PipelineOutputs:
    """
    Run the main target-triage workflow from ingestion to reports.

    The feature table and therapeutic-intent rankings are each built once and
    reused for Markdown cards, HTML reports, and summary figures.
    """
    _validate_positive_integer(
        "page_size",
        page_size,
    )
    _validate_positive_integer(
        "max_pages",
        max_pages,
    )
    _validate_positive_integer(
        "top_n_per_mode",
        top_n_per_mode,
    )

    project_root = Path(
        project_root
    ).resolve()

    feature_table_path = (
        project_root
        / "data"
        / "processed"
        / "targetintel_feature_table_v0_1.csv"
    )

    ranked_targets_path = (
        project_root
        / "results"
        / "ranked_targets.csv"
    )

    target_cards_dir = (
        project_root
        / "results"
        / "target_cards"
    )

    html_reports_dir = (
        project_root
        / "results"
        / "html_reports"
    )

    figures_dir = (
        project_root
        / "results"
        / "figures"
    )

    print()
    print("TargetIntel-IO end-to-end pipeline")
    print("----------------------------------")
    print(f"Page size:          {page_size}")
    print(f"Maximum pages:      {max_pages}")
    print(f"Refresh API cache:  {refresh}")
    print(f"Top targets/mode:   {top_n_per_mode}")

    print()
    print("[1/5] Building feature table")

    feature_df = build_feature_table(
        page_size=page_size,
        max_pages=max_pages,
        refresh=refresh,
    )

    saved_feature_table = save_feature_table(
        feature_df,
        feature_table_path,
    )

    print(
        f"Saved {len(feature_df)} targets to: "
        f"{saved_feature_table}"
    )

    print()
    print("[2/5] Scoring therapeutic-intent profiles")

    ranked_df = build_intent_rankings(
        feature_df
    )

    saved_ranked_targets = save_ranked_targets(
        ranked_df,
        ranked_targets_path,
    )

    print(
        f"Saved ranked targets to: "
        f"{saved_ranked_targets}"
    )

    print()
    print("[3/5] Generating target hypothesis cards")

    evidence_cards = (
        load_evidence_cards(evidence_store_path, ranked_df["target_symbol"].tolist())
        if evidence_store_path is not None
        else {}
    )

    card_kwargs = {
        "output_dir": target_cards_dir,
        "top_n_per_mode": top_n_per_mode,
    }
    if evidence_cards:
        card_kwargs["evidence_cards"] = evidence_cards
    card_paths = write_top_target_cards(ranked_df, **card_kwargs)

    print(
        f"Generated {len(card_paths)} Markdown cards in: "
        f"{target_cards_dir}"
    )

    print()
    print("[4/5] Generating HTML reports")

    html_kwargs = {
        "output_dir": html_reports_dir,
        "top_n_per_mode": top_n_per_mode,
    }
    if evidence_cards:
        html_kwargs["evidence_cards"] = evidence_cards
    html_paths = write_top_html_reports(ranked_df, **html_kwargs)

    print(
        f"Generated {len(html_paths)} HTML files in: "
        f"{html_reports_dir}"
    )

    print()
    print("[5/5] Generating summary figures")

    figure_paths = generate_summary_figures(
        ranked_df,
        output_dir=figures_dir,
        top_n=top_n_per_mode,
        heatmap_top_n_per_mode=min(
            top_n_per_mode,
            5,
        ),
    )

    print(
        f"Generated {len(figure_paths)} figures in: "
        f"{figures_dir}"
    )

    return PipelineOutputs(
        feature_table=Path(
            saved_feature_table
        ),
        ranked_targets=Path(
            saved_ranked_targets
        ),
        target_cards_dir=target_cards_dir,
        html_reports_dir=html_reports_dir,
        figures_dir=figures_dir,
    )


def run_validation_pipeline(
    *,
    page_size: int = 100,
    max_pages: int = 3,
    refresh: bool = False,
    project_root: Path = PROJECT_ROOT,
) -> tuple[Path, Path]:
    """
    Run the internal benchmark and scoring-weight sensitivity analysis.
    """
    _validate_positive_integer(
        "page_size",
        page_size,
    )
    _validate_positive_integer(
        "max_pages",
        max_pages,
    )

    project_root = Path(
        project_root
    ).resolve()

    python_executable = sys.executable

    benchmark_dir = (
        project_root
        / "results"
        / "benchmark"
    )

    sensitivity_dir = (
        project_root
        / "results"
        / "sensitivity"
    )

    benchmark_universe = (
        benchmark_dir
        / "ranked_targets_benchmark_universe.csv"
    )

    benchmark_config = (
        project_root
        / "configs"
        / "benchmark_targets.yaml"
    )

    build_universe_command = [
        python_executable,
        "scripts/09_build_benchmark_universe.py",
        "--page-size",
        str(page_size),
        "--max-pages",
        str(max_pages),
    ]

    if refresh:
        build_universe_command.append(
            "--refresh"
        )

    commands = [
        build_universe_command,
        [
            python_executable,
            "scripts/08_run_benchmark.py",
            "--input",
            str(benchmark_universe),
            "--config",
            str(benchmark_config),
            "--outdir",
            str(benchmark_dir),
            "--show-missing",
            "--show-errors",
        ],
        [
            python_executable,
            "scripts/11_run_sensitivity_analysis.py",
            "--input",
            str(benchmark_universe),
            "--benchmark-config",
            str(benchmark_config),
            "--outdir",
            str(sensitivity_dir),
            "--perturbation",
            "0.20",
            "--top-k",
            "5",
            "10",
            "20",
        ],
        [
            python_executable,
            "scripts/12_generate_sensitivity_figure.py",
            "--input",
            str(
                sensitivity_dir
                / "sensitivity_summary.csv"
            ),
            "--output",
            str(
                sensitivity_dir
                / "sensitivity_overview.png"
            ),
            "--dpi",
            "220",
        ],
    ]

    for command in commands:
        _run_command(
            command,
            project_root=project_root,
        )

    return (
        benchmark_dir,
        sensitivity_dir,
    )


def run_pipeline(
    *,
    page_size: int = 100,
    max_pages: int = 3,
    refresh: bool = False,
    top_n_per_mode: int = 10,
    validate: bool = False,
    evidence_store_path: str | Path | None = None,
    project_root: Path = PROJECT_ROOT,
) -> PipelineOutputs:
    """Run the complete workflow, optionally including validation."""
    outputs = run_core_pipeline(
        page_size=page_size,
        max_pages=max_pages,
        refresh=refresh,
        top_n_per_mode=top_n_per_mode,
        evidence_store_path=evidence_store_path,
        project_root=project_root,
    )

    if not validate:
        return outputs

    benchmark_dir, sensitivity_dir = (
        run_validation_pipeline(
            page_size=page_size,
            max_pages=max_pages,
            refresh=refresh,
            project_root=project_root,
        )
    )

    return PipelineOutputs(
        feature_table=outputs.feature_table,
        ranked_targets=outputs.ranked_targets,
        target_cards_dir=outputs.target_cards_dir,
        html_reports_dir=outputs.html_reports_dir,
        figures_dir=outputs.figures_dir,
        benchmark_dir=benchmark_dir,
        sensitivity_dir=sensitivity_dir,
    )
